### ISSUE TITLE
User Registeration API

### ISSUE THREAD

**Issue by Momen-Sanad** [0x3mr/Khair-ZC#11]
Create an API endpoint that allows users to register on the platform. This will involve:

1. Handling user input
2. Storing information in database
3. Hashing passwords before storage

Acceptance Criteria: 

- Endpoint accepts 'post' requests to create a new user
- Proper validation for required fields
- Password is stored securely using hashing

Priority: High

**Comment by Bodeayman** [comment]
Created the user's registration api , working as intended , meeting the acceptance criteria

**Comment by Bodeayman** [comment]
Created the user's registration api , working as intended , meeting the acceptance criteria
