### ISSUE TITLE
Implement User Login API

### ISSUE THREAD

**Issue by Momen-Sanad** [0x3mr/Khair-ZC#12]
Create an API endpoint for user login. This will:

1. Validate the user's credentials
2. Generate a token for session management
3. return user details upon successful login

Acceptance Criteria:

- Endpoint accepts 'post' requests with email and password
- Return a token for user session upon successful authentication
- Basic error handling for failed logins

Priority: High

**Comment by Bodeayman** [comment]
امال يسطا انتا هتعمل ايه

**Comment by Bodeayman** [comment]
Created the user's login api , working as intended , meeting the acceptance criteria
