### ISSUE TITLE
Implement Charity Registration API

### ISSUE THREAD

**Issue by Momen-Sanad** [0x3mr/Khair-ZC#13]
Create an API endpoint to allow charities to register on the platform. This will include necessary charity details.

Acceptance Criteria:

- Endpoint that accepts 'post' requests to create a new charity
- Proper validation of required fields
- Ensure charity's email is unique in the system

Priortiy: High

**Comment by Bodeayman** [comment]
Created the charity registration api , working as intended , meeting the acceptance criteria
