### ISSUE TITLE
Implement Admin API for Managing Campaigns

### ISSUE THREAD

**Issue by Momen-Sanad** [0x3mr/Khair-ZC#26]
Create an API endpoint that allows admins to edit (create, update, delete) campaigns. Admins should be able to control event visibility, details, and capacity.

Acceptance criteria:

- Endpoint allows admins to create, update, and delete campaigns.
- Admins can manage which charities are linked to specific campaigns.

Priority: Medium-High

**Comment by Ahmed-Abbas-2077** [comment]
Issue closed; update and delete endpoints implemented and tested (event.py)

**Comment by Momen-Sanad** [comment]
Endpoints are implemented correctly. However, there's no way to distinguish between regular users and admins. Please fix

**Comment by Ahmed-Abbas-2077** [comment]
Admin verification added
