### ISSUE TITLE
Implement Volunteer-Charity Link API

### ISSUE THREAD

**Issue by Momen-Sanad** [0x3mr/Khair-ZC#27]
Create an API endpoint that allows volunteers to connect with charities. This allows volunteers to follow, unfollow, and participate with specific charities.

Acceptance Criteria:

- Endpoint allows volunteers to follow/unfollow charities
- Ensure data consistency when volunteers register/unregister with charities

Priority: Medium

**Comment by Ahmed-Abbas-2077** [comment]
Issue closed; user creation and charity volunteering are implemented and tested.
