### ISSUE TITLE
Design Campaign Page

### ISSUE THREAD

**Issue by Momen-Sanad** [0x3mr/Khair-ZC#5]
Design and implement the campaign page layout to display campaign details, including description, donation link, and ability to register for the campaign

Priority: High

**Comment by khalidua** [comment]
implemnetation done waiting for the APIs

**Comment by Momen-Sanad** [comment]
API implementation for charity is created except for the 'donation link' field. Ahmed is currently working on it. Please show the rest of the fields on charity page for now.

**Comment by khalidua** [comment]
Done and Linked with backend
